# Generated by Django 5.1.2 on 2024-11-04 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PharmaSupport',
            fields=[
                ('P_id', models.AutoField(primary_key=True, serialize=False)),
                ('P_name', models.CharField(max_length=255)),
                ('P_Category', models.CharField(max_length=100)),
                ('P_image', models.CharField(max_length=255)),
                ('MRP', models.CharField(max_length=255)),
                ('Discounted_Price', models.CharField(max_length=255)),
                ('P_Description', models.TextField()),
            ],
        ),
    ]
