# Generated by Django 5.1.2 on 2024-11-04 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_pharmasupport'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pharmasupport',
            old_name='P_Category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='pharmasupport',
            old_name='Discounted_Price',
            new_name='discount_percentage',
        ),
        migrations.RenameField(
            model_name='pharmasupport',
            old_name='MRP',
            new_name='product_image',
        ),
        migrations.RemoveField(
            model_name='pharmasupport',
            name='P_Description',
        ),
        migrations.RemoveField(
            model_name='pharmasupport',
            name='P_id',
        ),
        migrations.RemoveField(
            model_name='pharmasupport',
            name='P_image',
        ),
        migrations.RemoveField(
            model_name='pharmasupport',
            name='P_name',
        ),
        migrations.AddField(
            model_name='pharmasupport',
            name='actual_product_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pharmasupport',
            name='description',
            field=models.CharField(default='To Be Updated', max_length=255),
        ),
        migrations.AddField(
            model_name='pharmasupport',
            name='discounted_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pharmasupport',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pharmasupport',
            name='product_link',
            field=models.URLField(default='N/A', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pharmasupport',
            name='product_name',
            field=models.CharField(default='Default Name', max_length=255),
        ),
    ]
