# Generated by Django 5.1.2 on 2024-11-04 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_p_category_pharmasupport_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmasupport',
            name='actual_product_price',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='pharmasupport',
            name='discounted_price',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='pharmasupport',
            name='product_link',
            field=models.CharField(max_length=255),
        ),
    ]
