# Generated by Django 5.1.2 on 2024-11-06 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_useraccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_name', models.CharField(default='Default Name', max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('d_image', models.CharField(default=None, max_length=255)),
                ('expertise', models.CharField(default=None, max_length=255)),
                ('qualification', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('clinic', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('language', models.CharField(max_length=255)),
                ('work_experience', models.CharField(max_length=255)),
                ('d_about', models.TextField()),
                ('rating', models.FloatField(default=0.0)),
            ],
        ),
    ]
