# Generated by Django 5.1.2 on 2024-11-06 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_doctors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctors',
            old_name='language',
            new_name='languages',
        ),
    ]
