# Generated by Django 5.1.2 on 2024-11-07 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_language_doctors_languages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h_name', models.CharField(default='Default Name', max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('h_image', models.CharField(default=None, max_length=255)),
                ('specialties', models.CharField(default=None, max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('h_description', models.TextField()),
                ('rating', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('l_name', models.CharField(default='Default Name', max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('l_image', models.CharField(default=None, max_length=255)),
                ('specialties', models.CharField(default=None, max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('l_description', models.TextField()),
                ('rating', models.FloatField(default=0.0)),
            ],
        ),
    ]
