# Generated by Django 5.1.2 on 2024-11-10 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_hospital_lab'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='Default Name', max_length=255)),
                ('item_count', models.CharField(default=0, max_length=255)),
                ('pharma_support', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pharmasupport')),
            ],
        ),
    ]
