# Generated by Django 5.1.2 on 2024-11-10 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='pharma_support',
        ),
        migrations.AddField(
            model_name='cart',
            name='p_id',
            field=models.CharField(default='0', max_length=255),
        ),
    ]
