# Generated by Django 4.2.16 on 2024-11-22 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_cart_item_count_alter_cart_p_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('category', models.CharField(choices=[('product', 'Product'), ('hospital', 'Hospital'), ('lab', 'Lab'), ('doctor', 'Doctor')], max_length=20)),
                ('subcategory_id', models.IntegerField()),
                ('review_comment', models.TextField()),
                ('review_stars', models.IntegerField()),
            ],
        ),
    ]
