# Generated by Django 3.2.25 on 2024-11-12 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_rename_product_cart_p_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='p_id',
            field=models.CharField(default='temporary_default', max_length=255),
        ),
    ]
