# Generated by Django 3.2.25 on 2024-11-16 14:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_cart_p_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('category', models.CharField(choices=[('product', 'Product'), ('hospital', 'Hospital'), ('lab', 'Lab'), ('doctor', 'Doctor')], max_length=20)),
                ('subcategory_id', models.IntegerField()),
                ('review_comment', models.TextField()),
                ('review_stars', models.IntegerField()),
            ],
        ),
    ]
