# Generated by Django 4.2.16 on 2024-11-18 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_labtestbooking'),
        ('app', '0018_alter_review_user_id'),
    ]

    operations = [
    ]
