# Generated by Django 4.2.16 on 2024-11-24 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_bill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('size', models.CharField(max_length=50)),
                ('units', models.CharField(max_length=50)),
                ('item_count', models.IntegerField()),
                ('mrp', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RenameField(
            model_name='bill',
            old_name='total_cost',
            new_name='total_value',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='orders',
        ),
        migrations.AddField(
            model_name='bill',
            name='products',
            field=models.JSONField(default=0),
            preserve_default=False,
        ),
    ]
