# Generated by Django 5.1.3 on 2024-11-25 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_product_rename_total_cost_bill_total_value_and_more'),
        ('app', '0020_alter_useraccount_email_alter_useraccount_username'),
    ]

    operations = [
    ]
