# Generated by Django 4.2.16 on 2024-11-27 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_labtestnotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr_no', models.IntegerField()),
                ('category', models.CharField(max_length=100)),
                ('question_english', models.TextField()),
                ('question_hindi', models.TextField()),
            ],
        ),
    ]
