# Generated by Django 5.1.4 on 2025-01-30 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0027_question_answers"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraccount",
            name="role",
            field=models.CharField(
                choices=[
                    ("patient", "Patient"),
                    ("chemist", "Chemist"),
                    ("lab", "Lab"),
                    ("hospital", "Hospital"),
                    ("doctor", "Doctor"),
                ],
                default="patient",
                max_length=50,
            ),
            preserve_default=False,
        ),
    ]
